### ISSUE TITLE
Deleted entry after using rebiber

### ISSUE THREAD

**Issue by RaghuSpaceRajan** [yuchenlin/rebiber#29]
Hi, 

Thanks for the great tool! I faced an issue where an entry was deleted after using rebiber though. It's this one:

```
@article{loon,
  title={Autonomous navigation of stratospheric balloons using reinforcement learning.},
  author={Marc G. Bellemare and Salvatore Candido and P. S. Castro and J. Gong and Marlos C. Machado and Subhodeep Moitra and Sameera S. Ponda and Ziyu Wang},
  journal={Nature},
  year={2020},
  volume={588 7836},
  pages={
          77-82
        }
}
```

Do you have any idea what could be wrong?

**Comment by RaghuSpaceRajan** [comment]
I tried to use rebiber on a file containing only this entry and also multiple entries, but the entry is always deleted after conversion.

**Comment by yuchenlin** [comment]
Thanks for reporting this. @yangxqiao would u plz take a quick look at this issue? I guess it is about the formatting of the `page` entry.

**Comment by yangxqiao** [comment]
Thanks again for reporting this! The bib entry is deleted because the `page` entry contains multiple lines instead of one line, and the previous load_bib_file() function was unable to handle this special case. We updated the load_bib_file(), and now it should be able to detect this certain case, process it correctly, and include this entry in its output. This change will be included in our next release. Thanks and please feel free to reach out again if new issues pop up!

**Comment by RaghuSpaceRajan** [comment]
Hi @yangxqiao , thank you very much for the fix!
